### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rebornix** [rebornix/OpenLiveWriter#1]
Below is a draft roadmap of Static Site related blog providers
### Authentication
- [x] Basic Authentication
- [ ] OAuth 2.0
### CRUD ( GitHub API )
- [x] CRUD blog post ( `_posts` folder )
- [ ] Draft ( `_draft` folder )
### YFM and configuration
- [ ] [Yaml Front Matter](http://jekyllrb.com/docs/frontmatter/)
- [ ] [Jekyll Configuration (Follow GitHub Page)](http://jekyllrb.com/docs/configuration/)
### Authoring/Preview ( UI part )
- [ ] Markdown Authoring
- [ ] Preview
## Static Site Abstract

To be continued...

**Comment by pekiZG** [comment]
@rebornix As I understand 
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5
should solve OAuth 2.0

As we discussed I will look into "Authoring/Preview ( UI part )".
When that's done we should be able to feed the output to some Static Site Generator.

GitHub API for MarkDown is here
https://developer.github.com/v3/markdown/

**Comment by rebornix** [comment]
@pekiZG you are right, let's leave it there, leverage the oauth code after [5](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5) is merged. Wait for your progress on Authoring part :+1: 

Anyone who is interested in Jekyll or happens to be a rubist can take YFM and configuration.

**Comment by lankaapura** [comment]
@rebornix @pekiZG I'll take a look at CRUD ( GitHub API ). I still haven't got a chance go through the code. I'll share my insights after that.

As we discussed, we need some common interface to save blog content to relevant providers. For the time being we will implement this interface for Jekyll on Github. Am I right? 

May be we can issues for each of this tasks, so we can relevant details there. And start a gitter channel also? What yourl think?

**Comment by rebornix** [comment]
@lankaapura yup, let's focus on interface for Jekyll this time. 

Once you start to code for CRUD, you can create an issue for status tracking. We use this issue for overall task tracking. 

I'm Okay with gitter, it would be great if you help set it up !

**Comment by pekiZG** [comment]
Just putting my toughts here.

GitHub uses github flavored markdown
https://help.github.com/articles/github-flavored-markdown/

It should comply to CommonMark standard.
http://commonmark.org/

CommonMark implementations
https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations

@lankaapura
Sure look at API and report your findings. I will write here my progress after each session.

## 

It would be best to use official gitter.

<p><a href="https://gitter.im/OpenLiveWriter/OpenLiveWriter?utm_source=badge&amp;utm_medium=badge&amp;utm_campaign=pr-badge"><img src="https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667" alt="Gitter" data-canonical-src="https://badges.gitter.im/Join%20Chat.svg" style="max-width:100%;"></a></p>

**Comment by pekiZG** [comment]
@here: There are gitter apps you can use :)
https://gitter.im/#apps-panel

**Comment by robertiagar** [comment]
I can look a the _YAML_ Front Matter and Configurations.

**Comment by lankaapura** [comment]
@rebornix cool

@pekiZG yeah I saw the official one, lets use it.

**Comment by pekiZG** [comment]
:+1:

**Comment by rebornix** [comment]
@robertiagar Awesome! 

FYI, Jekyll uses YML as blog post's metadata, there are even some tricky parts while Jekyll handles with title and filename. You can sync with me as I contributed a few related codes to Jekyll.

**Comment by robertiagar** [comment]
There's not point into having jekyll embed in OLW. We just need to figure out how to simulate jekyll in the app.

**Comment by pekiZG** [comment]
My Idea was something like this.
- User should install jekyll/hugo or some other static site generator beside OLW.
- OLW should be able to control/run jekyll/hugo per user request.

**Comment by ScottIsAFool** [comment]
If you guys are waiting on https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5 from the OLW branch for this, you should know that the OAuth stuff for that will only be for google, not an oauth structure for the app.

**Comment by rebornix** [comment]
@ScottIsAFool thanks for the information :+1: :smile: 

For now I'll just focus on the basic authentication with GitHub personal access token, which is enough convenient. After we finish the OAuth part for GitHub, then let's see how to make some abstraction to share logic of OAuth.

**Comment by JohnBlood** [comment]
Question: Will be targeting a local version of the static site generator or a hosted version? I'm planning to test this and wanted to know if I should install them locally or install them on my host service.

Also, would it be possible to give the user the ability to issue a command to the generator to serve or build the site? It won't be needed with Github because when GH detects a new page or change in the files, it automatically rebulds.

**Comment by rebornix** [comment]
As a provider, I think it should talk to server ( like GitHub ) directly when you publish, so yes hosted version. Local version of static site generators have too much dependency, like Jekyll is based on Ruby which doesn't work well on Windows, I suggest make it pluggable. Allow users to use plugins to integrate local site with OLW, make sense ？

**Comment by rebornix** [comment]
@pekiZG  @lankaapura  @robertiagar  @JohnBlood friends, just made some progress and send out the commit https://github.com/rebornix/OpenLiveWriter/commit/648043bf1fda506f5477582c2649e986d0c543a1 .

Sync my commit and run OLW from source code. Just follow below steps to add GitHub provider then you should be able to post a temp post to your repository in GitHub.
1. Add new blog provider. ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step1.PNG)
2. Type in the info about your GitHub Page repo (currently we don't support branch other master) ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step2.PNG)
3. Blog auto-detection can't identity which blog engine it belongs to, then it will pop up a window to let choose manually. ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step3.PNG)
   ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step4.PNG)
4. Click Next. and choose this blog engine as default one. ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step5.PNG)
5. Try to publish a new post to your GitHub repo and check its commit history, the new file should be there. ![](http://7sbn7z.com5.z0.glb.clouddn.com/githubpage-step6.PNG)

**Comment by rebornix** [comment]
This is a draft version, just for you guys to get an idea how GitHub Provider will work in OLW. I implement `getUserBlogs`, `NewPost` and `GetPost` three methods for `GitHubPageClient`, but there are too many `TODO` and `NotImplemented` left behind. Running into exceptions or UI frozen sometimes is expected :)

**Comment by pekiZG** [comment]
@rebornix it looks great, good job :)

EDIT:
http://api.ghost.org/v0.1/docs
docs for future JsonBlogClient.cs

**Comment by martinwoodward** [comment]
Wow - great to see this coming together folks.  Keep up the good work!

**Comment by rebornix** [comment]
thanks @martinwoodward . we'll send the WIP pr once we finish the basic CRUD features, maybe next week.

**Comment by lankaapura** [comment]
@rebornix Great job!! :+1:

**Comment by jongio** [comment]
@rebornix - What's the latest on this?  Are you still working on it?

**Comment by rebornix** [comment]
@jonbgallant currently this feature is blocked by https://github.com/OpenLiveWriter/OpenLiveWriter/issues/11 , once the markdown support is enabled, we can have GH support real quick actually. I'll sync with Dend internally about the timing.

**Comment by tonidy** [comment]
@rebornix would you like give latest information about this forking?

**Comment by aovestdipaperino** [comment]
Why is markdown support required? Jekyll/Hugo easily support HTML + front matter. I use this for my blog so I didn't have to go through an HTML -> MD conversion (which will be converted back in HTML, which is... _silly_).
